# general
gpu_id: 1
use_gpu: True
seed: 42
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# dataset
load_col:
    inter: [review_id, user_id, business_id, stars, useful, funny, cool, date]
    item: [business_id, categories]
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: business_id
RATING_FIELD: stars
TIME_FIELD: date

# Filtering
val_interval: {'date': "[1546264800,1577714400]"}
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

group_size: 25

perturb_eps: 0.05