n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
mask_ratio: 0.4
generator_path: 'saved/BERT4Rec-May-11-2022_17-39-30.pth'
encoder_loss_weight: 1
discriminator_loss_weight: 1
generate_loss_weight: 0
contrastive_loss_weight: 0
contras_loss_temp: 0.05
contras_target: 'avgk'
contras_k: 5
share_param: 'all'
discriminator_combine: 'cat'
discriminator_bidirectional: True
always_con: False
generate_method: 'bert' # bert or random
dcl_state: 'disc'
mask_strategy: 'prob'
auto_weight: False